"use client"
import { useState } from "react"
type SavedLink = { id: string; expiresAt: string; revokeToken: string }
export function ManageReportLinks() {
  const [links,setLinks]=useState<SavedLink[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState("")
  function refresh(){try{const rows:SavedLink[]=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('chairpedia-share-'))continue;try{const x=JSON.parse(localStorage.getItem(key)||'null');if(/^[a-f0-9-]{36}$/.test(x?.id)&&/^[a-f0-9]{64}$/.test(x?.revokeToken)&&Number.isFinite(Date.parse(x?.expiresAt)))rows.push(x)}catch{}}setLinks(rows.sort((a,b)=>Date.parse(b.expiresAt)-Date.parse(a.expiresAt)))}catch{setMessage('Saved links are unavailable in this browser.')}}
  async function revoke(link:SavedLink){setMessage('Turning off link...');try{const r=await fetch(`/api/chair-fit/reports/${link.id}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({revokeToken:link.revokeToken})});if(!r.ok&&r.status!==404)throw Error();localStorage.removeItem(`chairpedia-share-${link.id}`);refresh();setMessage('The link is now turned off.')}catch{setMessage('Could not turn off the link. Please try again.')}}
  return <div className="print:hidden"><button type="button" aria-expanded={open} onClick={()=>{refresh();setOpen(!open)}} className="min-h-11 px-4 text-sm text-[#244f73] underline">Manage shared links</button>{open&&<section className="mt-3 max-w-xl border border-[#c8c1b5] bg-[#f8f5ef] p-5"><h2 className="font-serif text-2xl">Your shared links</h2><p className="mt-2 text-sm leading-6 text-[#575249]">Links created in this browser. Clearing browser storage removes these controls. Links still expire automatically.</p>{!links.length&&<p className="mt-4 text-sm">No saved links in this browser.</p>}<ul className="mt-4 space-y-4">{links.map(link=>{const expired=Date.parse(link.expiresAt)<=Date.now();const url=`${window.location.origin}/chair-fit-report/${link.id}`;return <li key={link.id} className="border-t border-[#c8c1b5] pt-3"><p className="text-xs">{expired?'Expired':'Expires'} {link.expiresAt.slice(0,10)}</p><input aria-label="Saved share link" readOnly value={url} onFocus={e=>e.target.select()} className="mt-2 w-full border border-[#c8c1b5] bg-white p-2 text-xs"/><div className="flex flex-wrap gap-3">{!expired&&<><a href={url} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-sm underline">Open report</a><button type="button" className="min-h-11 text-sm underline" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Link copied.')}catch{setMessage('Select and copy the link above.')}}}>Copy link</button></>}<button type="button" onClick={()=>revoke(link)} className="min-h-11 text-sm underline">{expired?'Remove expired link':'Turn off link'}</button></div></li>})}</ul><p role="status" className="mt-3 text-sm">{message}</p></section>}</div>
}
