import { defineChair } from "../helpers"
import type { HardcodedChair } from "../types"

export const EUROPE_AMERICA_CHAIRS: HardcodedChair[] = [
  // Humanscale
  defineChair({ slug: "humanscale-freedom", brand: "humanscale", category: "executive", name: "Humanscale Freedom", nameEn: "Humanscale Freedom Headrest", descriptionEn: "Weight-sensitive recline with synchronous armrests that move with the back. Minimal controls, maximum comfort.", priceUsd: 1249, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Auto recline", "Synchronous arms", "Clean design"], cons: ["Limited manual tuning", "Seat can feel firm"], bestFor: "Minimalists who dislike knob-heavy chairs", seoTitle: "Humanscale Freedom Chair Review", seoDescription: "Freedom weight-sensitive recline and ergonomic specs." }),
  defineChair({ slug: "humanscale-world-one", brand: "humanscale", category: "office", name: "Humanscale World One", nameEn: "Humanscale World One", descriptionEn: "Entry Humanscale task chair with Form-Sensing mesh and simplified adjustments for everyday offices.", priceUsd: 499, priceKrw: 0, chairType: "Mesh Back", preset: "study", pros: ["Affordable Humanscale", "Mesh seat"], cons: ["Fewer features than Freedom"], bestFor: "Teams scaling ergonomic seating", seoTitle: "Humanscale World One Specs", seoDescription: "World One mesh task chair features and pricing." }),
  defineChair({ slug: "humanscale-liberty", brand: "humanscale", category: "office", name: "Humanscale Liberty", nameEn: "Humanscale Liberty", descriptionEn: "Tri-panel mesh back with automatic recline and optional headrest for responsive support.", priceUsd: 999, priceKrw: 0, chairType: "Mesh Back", pros: ["Tri-panel back", "Responsive mesh"], cons: ["Arms less adjustable than Freedom"], bestFor: "Mesh lovers wanting auto-adjust", seoTitle: "Humanscale Liberty Office Chair", seoDescription: "Liberty tri-panel mesh and auto-recline overview." }),
  defineChair({ slug: "humanscale-diffrient-smart", brand: "humanscale", category: "office", name: "Humanscale Diffrient Smart", nameEn: "Humanscale Diffrient Smart", descriptionEn: "Niels Diffrient design with automatic lumbar and weight-activated recline in a compact footprint.", priceUsd: 899, priceKrw: 0, chairType: "Task Chair", pros: ["Auto lumbar", "Compact", "Designer pedigree"], cons: ["Seat depth not adjustable on all trims"], bestFor: "Design studios and modern offices", seoTitle: "Humanscale Diffrient Smart Specs", seoDescription: "Diffrient Smart automatic ergonomics and dimensions." }),
  defineChair({ slug: "humanscale-diffrient-world", brand: "humanscale", category: "office", name: "Humanscale Diffrient World", nameEn: "Humanscale Diffrient World", descriptionEn: "Simplified Diffrient line with mesh seat and back for breathable all-day support.", priceUsd: 799, priceKrw: 0, chairType: "Mesh Back", pros: ["Full mesh", "Lightweight"], cons: ["Less padding preference for some"], bestFor: "Warm climates and long summer sessions", seoTitle: "Humanscale Diffrient World Chair", seoDescription: "Diffrient World mesh specifications." }),
  // HÅG / Flokk
  defineChair({ slug: "hag-capisco", brand: "hag-flokk", category: "standing", name: "HÅG Capisco", nameEn: "HÅG Capisco", descriptionEn: "Saddle-style seat encourages open hip angle and supports perching at sit-stand desks. Iconic Scandinavian design.", priceUsd: 1100, priceKrw: 0, chairType: "Saddle", preset: "standing", pros: ["Ideal for sit-stand", "Unique posture support", "Sustainable build"], cons: ["Learning curve", "Not traditional sitting"], bestFor: "Sit-stand desk users and designers", seoTitle: "HÅG Capisco Saddle Chair Review", seoDescription: "Capisco saddle seat specs and sit-stand usage guide." }),
  defineChair({ slug: "hag-capisco-puls", brand: "hag-flokk", category: "standing", name: "HÅG Capisco Puls", nameEn: "HÅG Capisco Puls", descriptionEn: "Plastic-shell Capisco variant for tougher environments like workshops and labs while keeping saddle ergonomics.", priceUsd: 950, priceKrw: 0, chairType: "Saddle", preset: "standing", pros: ["Durable shell", "Same saddle benefits"], cons: ["Less premium feel than upholstered Capisco"], bestFor: "Labs, workshops, and active workspaces", seoTitle: "HÅG Capisco Puls Specs", seoDescription: "Capisco Puls durable saddle chair overview." }),
  defineChair({ slug: "hag-sofi", brand: "hag-flokk", category: "office", name: "HÅG SoFi", nameEn: "HÅG SoFi", descriptionEn: "Mesh task chair with HÅG inBalance mechanism and sustainable materials for Nordic offices.", priceUsd: 900, priceKrw: 0, chairType: "Mesh Back", pros: ["Sustainable", "Balanced movement"], cons: ["Limited availability outside EU"], bestFor: "Scandinavian-style offices", seoTitle: "HÅG SoFi Office Chair", seoDescription: "SoFi mesh and inBalance mechanism specs." }),
  defineChair({ slug: "hag-tion", brand: "hag-flokk", category: "office", name: "HÅG Tion", nameEn: "HÅG Tion", descriptionEn: "Streamlined task chair with intuitive controls and compact back for open-plan workplaces.", priceUsd: 750, priceKrw: 0, chairType: "Task Chair", pros: ["Easy to use", "Compact"], cons: ["Less flagship than Capisco"], bestFor: "Open-plan task seating", seoTitle: "HÅG Tion Task Chair", seoDescription: "Tion office chair ergonomic features." }),
  defineChair({ slug: "flokk-rh-logic-400", brand: "hag-flokk", category: "office", name: "Flokk RH Logic 400", nameEn: "Flokk RH Logic 400", descriptionEn: "Classic Scandinavian ergonomic chair with exceptional build quality and precise manual adjustments.", priceUsd: 1200, priceKrw: 0, chairType: "Task Chair", pros: ["Legendary durability", "Precise adjustments"], cons: ["Traditional look", "Premium EU pricing"], bestFor: "Users wanting long-lasting manual ergonomics", seoTitle: "Flokk RH Logic 400 Review", seoDescription: "RH Logic 400 specs and Scandinavian ergonomics." }),
  defineChair({ slug: "flokk-rh-mereo", brand: "hag-flokk", category: "office", name: "Flokk RH Mereo", nameEn: "Flokk RH Mereo", descriptionEn: "RH line chair with split back and strong lumbar for users preferring pronounced lower-back support.", priceUsd: 1100, priceKrw: 0, chairType: "Task Chair", pros: ["Strong lumbar", "RH quality"], cons: ["Firm back for some"], bestFor: "Lower-back support priority users", seoTitle: "Flokk RH Mereo Office Chair", seoDescription: "RH Mereo lumbar support and specifications." }),
  // Wilkhahn
  defineChair({ slug: "wilkhahn-on", brand: "wilkhahn", category: "office", name: "Wilkhahn ON", nameEn: "Wilkhahn ON", descriptionEn: "German engineering with Trimension kinematics for three-dimensional movement while seated.", priceUsd: 1300, priceKrw: 0, chairType: "Task Chair", pros: ["3D movement", "Premium German build"], cons: ["Expensive", "Complex mechanism"], bestFor: "Movement-oriented ergonomic offices", seoTitle: "Wilkhahn ON Trimension Chair", seoDescription: "ON chair 3D kinematics and ergonomic design." }),
  defineChair({ slug: "wilkhahn-at", brand: "wilkhahn", category: "office", name: "Wilkhahn AT", nameEn: "Wilkhahn AT", descriptionEn: "Compact Wilkhahn task chair with automatic weight adjustment and clean aluminum details.", priceUsd: 1000, priceKrw: 0, chairType: "Task Chair", pros: ["Auto weight adjust", "Compact"], cons: ["Less known outside EU"], bestFor: "European corporate offices", seoTitle: "Wilkhahn AT Office Chair Specs", seoDescription: "AT chair automatic adjustment features." }),
  defineChair({ slug: "wilkhahn-fs", brand: "wilkhahn", category: "conference", name: "Wilkhahn FS", nameEn: "Wilkhahn FS", descriptionEn: "Conference seating with linear aesthetics for meeting tables and boardrooms.", priceUsd: 900, priceKrw: 0, chairType: "Conference", preset: "conference", pros: ["Meeting-room design", "Stackable options"], cons: ["Not for task work"], bestFor: "Conference and meeting rooms", seoTitle: "Wilkhahn FS Conference Chair", seoDescription: "FS conference seating specifications." }),
  defineChair({ slug: "wilkhahn-modus", brand: "wilkhahn", category: "conference", name: "Wilkhahn Modus", nameEn: "Wilkhahn Modus", descriptionEn: "Modular conference chair system with slim profile and optional linking for large rooms.", priceUsd: 850, priceKrw: 0, chairType: "Conference", preset: "conference", pros: ["Modular layouts", "Slim profile"], cons: ["Limited cushioning"], bestFor: "Large conference installations", seoTitle: "Wilkhahn Modus Conference Seating", seoDescription: "Modus modular conference chair system." }),
  defineChair({ slug: "wilkhahn-graph", brand: "wilkhahn", category: "conference", name: "Wilkhahn Graph", nameEn: "Wilkhahn Graph", descriptionEn: "Cantilever conference chair with flexible back for meeting comfort without wheels.", priceUsd: 950, priceKrw: 0, chairType: "Conference", preset: "conference", pros: ["Cantilever elegance", "Flexible back"], cons: ["No height adjust on base models"], bestFor: "Meeting rooms and training spaces", seoTitle: "Wilkhahn Graph Conference Chair", seoDescription: "Graph cantilever meeting chair specs." }),
  // Vitra
  defineChair({ slug: "vitra-id-chair-concept", brand: "vitra", category: "office", name: "Vitra ID Chair Concept", nameEn: "Vitra ID Chair Concept", descriptionEn: "Antonio Citterio ID Chair with configurable modules for lumbar, seat, and arm styles.", priceUsd: 1400, priceKrw: 0, chairType: "Task Chair", pros: ["Highly modular", "Design prestige"], cons: ["Configuration complexity", "Premium price"], bestFor: "Design-led European offices", seoTitle: "Vitra ID Chair Concept Specs", seoDescription: "ID Chair Concept modules and ergonomics." }),
  defineChair({ slug: "vitra-id-soft", brand: "vitra", category: "office", name: "Vitra ID Soft", nameEn: "Vitra ID Soft", descriptionEn: "Padded ID variant with softer seat and back for users preferring cushioned surfaces over mesh.", priceUsd: 1500, priceKrw: 0, chairType: "Task Chair", preset: "premium_task", pros: ["Plush comfort", "Modular"], cons: ["Less breathable", "Heavy"], bestFor: "Users preferring cushioned task chairs", seoTitle: "Vitra ID Soft Office Chair", seoDescription: "ID Soft padding and specification overview." }),
  defineChair({ slug: "vitra-id-trim", brand: "vitra", category: "office", name: "Vitra ID Trim", nameEn: "Vitra ID Trim", descriptionEn: "Slim-profile ID line with lighter visual weight for contemporary workspaces.", priceUsd: 1300, priceKrw: 0, chairType: "Task Chair", pros: ["Slim aesthetic", "ID ergonomics"], cons: ["Less padding than Soft"], bestFor: "Modern minimalist offices", seoTitle: "Vitra ID Trim Task Chair", seoDescription: "ID Trim slim office chair features." }),
  defineChair({ slug: "vitra-pacific-chair", brand: "vitra", category: "office", name: "Vitra Pacific Chair", nameEn: "Vitra Pacific Chair", descriptionEn: "Edward Barber & Jay Osgerby design with height-adjustable arms and responsive mesh back.", priceUsd: 1200, priceKrw: 0, chairType: "Mesh Back", pros: ["Design award pedigree", "Comfortable mesh"], cons: ["Premium Vitra pricing"], bestFor: "Creative agencies and design firms", seoTitle: "Vitra Pacific Chair Review", seoDescription: "Pacific Chair mesh and adjustment specs." }),
  defineChair({ slug: "vitra-eames-aluminium-group", brand: "vitra", category: "executive", name: "Vitra Eames Aluminium Group", nameEn: "Vitra Eames Aluminium Group Chair", descriptionEn: "Charles & Ray Eames classic with cast aluminum frame and leather or mesh options. Timeless executive seating.", priceUsd: 3500, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Design icon", "Premium materials"], cons: ["Not modern ergonomic adjustability", "Very expensive"], bestFor: "Executive offices and design collectors", seoTitle: "Eames Aluminium Group Chair — Vitra", seoDescription: "Eames Aluminium Group specifications and history." }),
  defineChair({ slug: "vitra-physix", brand: "vitra", category: "office", name: "Vitra Physix", nameEn: "Vitra Physix", descriptionEn: "Physix flexible frame distributes load across back without traditional mechanisms.", priceUsd: 1600, priceKrw: 0, chairType: "Task Chair", pros: ["Innovative frame", "Clean look"], cons: ["Limited recline vs Leap"], bestFor: "Architect offices seeking design statement", seoTitle: "Vitra Physix Office Chair", seoDescription: "Physix flexible frame ergonomic overview." }),
  defineChair({ slug: "vitra-physix-conference", brand: "vitra", category: "conference", name: "Vitra Physix Conference", nameEn: "Vitra Physix Conference", descriptionEn: "Conference variant of Physix with meeting-height configuration and refined upholstery.", priceUsd: 1700, priceKrw: 0, chairType: "Conference", preset: "conference", pros: ["Matches Physix task aesthetic", "Meeting appropriate"], cons: ["Not for all-day desk use"], bestFor: "Design-led meeting rooms", seoTitle: "Vitra Physix Conference Chair", seoDescription: "Physix conference seating specs." }),
  // Knoll
  defineChair({ slug: "knoll-regeneration", brand: "knoll", category: "office", name: "Knoll ReGeneration", nameEn: "Knoll ReGeneration", descriptionEn: "Flexible polymer back flexes with movement; sustainable materials and modern Knoll aesthetics.", priceUsd: 1099, priceKrw: 0, chairType: "Task Chair", pros: ["Flexible back", "Sustainable"], cons: ["Less adjustability than Leap"], bestFor: "Modern offices and sustainability goals", seoTitle: "Knoll ReGeneration Chair Specs", seoDescription: "ReGeneration flexible back and eco features." }),
  defineChair({ slug: "knoll-life-chair", brand: "knoll", category: "office", name: "Knoll Life Chair", nameEn: "Knoll Life Chair", descriptionEn: "IntelliForm back and Dynamic Suspension seat for responsive support in task environments.", priceUsd: 999, priceKrw: 0, chairType: "Task Chair", pros: ["Responsive back", "Knoll design"], cons: ["Aging platform vs newer chairs"], bestFor: "Knoll-specified corporate fit-outs", seoTitle: "Knoll Life Chair Review", seoDescription: "Life Chair IntelliForm back specifications." }),
  defineChair({ slug: "knoll-chadwick", brand: "knoll", category: "office", name: "Knoll Chadwick", nameEn: "Knoll Chadwick", descriptionEn: "Don Chadwick design with mesh seat and lumbar for breathable task seating.", priceUsd: 899, priceKrw: 0, chairType: "Mesh Back", pros: ["Designer legacy", "Breathable"], cons: ["Discontinued in some markets"], bestFor: "Mesh task seating on Knoll contracts", seoTitle: "Knoll Chadwick Mesh Chair", seoDescription: "Chadwick mesh task chair overview." }),
  defineChair({ slug: "knoll-rpm-executive", brand: "knoll", category: "executive", name: "Knoll RPM Executive", nameEn: "Knoll RPM Executive", descriptionEn: "High-back executive chair with polished base and generous padding for leadership offices.", priceUsd: 2200, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Executive presence", "Knoll quality"], cons: ["Heavy", "Traditional"], bestFor: "Executive suites on Knoll contracts", seoTitle: "Knoll RPM Executive Chair", seoDescription: "RPM executive seating specifications." }),
  // Haworth
  defineChair({ slug: "haworth-fern", brand: "haworth", category: "office", name: "Haworth Fern", nameEn: "Haworth Fern", descriptionEn: "Digitally knit suspension back with optional headrest and strong sustainability credentials.", priceUsd: 1195, priceKrw: 0, chairType: "Mesh Back", pros: ["Knit back comfort", "Sustainable", "Optional headrest"], cons: ["Premium pricing"], bestFor: "Eco-conscious ergonomic offices", seoTitle: "Haworth Fern Chair Review", seoDescription: "Fern knit back suspension and ergonomic specs." }),
  defineChair({ slug: "haworth-soji", brand: "haworth", category: "office", name: "Haworth Soji", nameEn: "Haworth Soji", descriptionEn: "Lightweight mesh task chair with essential adjustments at accessible Haworth pricing.", priceUsd: 499, priceKrw: 0, chairType: "Mesh Back", preset: "study", pros: ["Affordable mesh", "Light frame"], cons: ["Fewer adjustments than Fern"], bestFor: "Budget mesh for growing teams", seoTitle: "Haworth Soji Mesh Task Chair", seoDescription: "Soji mesh chair specs and value overview." }),
  defineChair({ slug: "haworth-very-task", brand: "haworth", category: "office", name: "Haworth Very Task", nameEn: "Haworth Very Task", descriptionEn: "Versatile task chair with intuitive weight-sensing recline and compact scale.", priceUsd: 699, priceKrw: 0, chairType: "Task Chair", pros: ["Intuitive recline", "Compact"], cons: ["Less premium than Fern"], bestFor: "Standard office task deployments", seoTitle: "Haworth Very Task Chair Specs", seoDescription: "Very Task weight-sensing recline features." }),
  defineChair({ slug: "haworth-comforto-59", brand: "haworth", category: "office", name: "Haworth Comforto 59", nameEn: "Haworth Comforto 59", descriptionEn: "German Haworth line with robust mechanism for intensive daily office use.", priceUsd: 850, priceKrw: 0, chairType: "Task Chair", pros: ["Robust mechanism", "EU build quality"], cons: ["Less known in US"], bestFor: "European Haworth installations", seoTitle: "Haworth Comforto 59 Office Chair", seoDescription: "Comforto 59 task chair specifications." }),
  defineChair({ slug: "haworth-comforto-29", brand: "haworth", category: "conference", name: "Haworth Comforto 29", nameEn: "Haworth Comforto 29", descriptionEn: "Conference chair from Comforto line with meeting-appropriate scale and upholstery.", priceUsd: 750, priceKrw: 0, chairType: "Conference", preset: "conference", pros: ["Matches Comforto task line", "Meeting scale"], cons: ["Not for 8h desk work"], bestFor: "Meeting rooms in EU offices", seoTitle: "Haworth Comforto 29 Conference", seoDescription: "Comforto 29 conference seating specs." }),
  // Sedus
  defineChair({ slug: "sedus-open-up", brand: "sedus", category: "office", name: "Sedus Open Up", nameEn: "Sedus open up", descriptionEn: "German task chair encouraging open posture with flexible back and modern aesthetics.", priceUsd: 800, priceKrw: 0, chairType: "Task Chair", pros: ["Open posture design", "German engineering"], cons: ["Limited US availability"], bestFor: "European open-plan offices", seoTitle: "Sedus open up Office Chair", seoDescription: "open up ergonomic task chair specs." }),
  defineChair({ slug: "sedus-sedo", brand: "sedus", category: "office", name: "Sedus Se:do", nameEn: "Sedus se:do", descriptionEn: "Slim task chair with weight-activated synchro tilt and optional headrest.", priceUsd: 750, priceKrw: 0, chairType: "Task Chair", pros: ["Slim profile", "Auto tilt"], cons: ["Niche brand globally"], bestFor: "German corporate fit-outs", seoTitle: "Sedus se:do Task Chair", seoDescription: "se:do office chair specifications." }),
  defineChair({ slug: "sedus-network", brand: "sedus", category: "office", name: "Sedus Net:work", nameEn: "Sedus Net:work", descriptionEn: "Mesh office chair with Net:work suspension for breathability in warm offices.", priceUsd: 700, priceKrw: 0, chairType: "Mesh Back", pros: ["Breathable mesh", "Good value in EU"], cons: ["Basic globally"], bestFor: "EU mesh office standard", seoTitle: "Sedus Net:work Mesh Chair", seoDescription: "Net:work mesh suspension specs." }),
  defineChair({ slug: "sedus-black-dot", brand: "sedus", category: "office", name: "Sedus Black Dot", nameEn: "Sedus Black Dot", descriptionEn: "Compact task chair with distinctive back detail and essential ergonomic adjustments.", priceUsd: 650, priceKrw: 0, chairType: "Task Chair", preset: "study", pros: ["Compact", "Distinctive design"], cons: ["Limited adjustability"], bestFor: "Small offices and home EU buyers", seoTitle: "Sedus Black Dot Office Chair", seoDescription: "Black Dot compact ergonomic specs." }),
  // Global
  defineChair({ slug: "global-concorde-presidential", brand: "global", category: "executive", name: "Global Concorde Presidential", nameEn: "Global Concorde Presidential", descriptionEn: "Canadian-made high-back executive chair with generous padding and presidential scale.", priceUsd: 1500, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Executive scale", "North American support"], cons: ["Traditional styling"], bestFor: "North American executive offices", seoTitle: "Global Concorde Presidential Chair", seoDescription: "Concorde Presidential executive specs." }),
  defineChair({ slug: "global-accord", brand: "global", category: "office", name: "Global Accord", nameEn: "Global Accord", descriptionEn: "Mid-range Global task chair with synchro tilt and adjustable arms for corporate deployments.", priceUsd: 550, priceKrw: 0, chairType: "Task Chair", pros: ["Contract-friendly", "Reliable"], cons: ["Generic aesthetics"], bestFor: "Large North American office contracts", seoTitle: "Global Accord Task Chair", seoDescription: "Accord office chair specifications." }),
  defineChair({ slug: "global-sora", brand: "global", category: "office", name: "Global Sora", nameEn: "Global Sora", descriptionEn: "Mesh task chair from Global with weight-activated controls and breathable seat.", priceUsd: 600, priceKrw: 0, chairType: "Mesh Back", pros: ["Mesh at mid price", "Easy procurement"], cons: ["Below premium tier ergonomics"], bestFor: "Contract mesh seating", seoTitle: "Global Sora Mesh Chair", seoDescription: "Sora mesh task chair overview." }),
  // König+Neurath
  defineChair({ slug: "konig-neurath-okay-2", brand: "konig-neurath", category: "office", name: "König+Neurath Okay.2", nameEn: "König+Neurath Okay.2", descriptionEn: "German office chair with intuitive controls and sustainable manufacturing for EU workplaces.", priceUsd: 700, priceKrw: 0, chairType: "Task Chair", pros: ["EU sustainability", "Solid build"], cons: ["Rare outside Europe"], bestFor: "German corporate offices", seoTitle: "König+Neurath Okay.2 Specs", seoDescription: "Okay.2 task chair ergonomic features." }),
  defineChair({ slug: "konig-neurath-teo", brand: "konig-neurath", category: "office", name: "König+Neurath Teo", nameEn: "König+Neurath Teo", descriptionEn: "Lightweight task chair with mesh back and minimal environmental footprint.", priceUsd: 650, priceKrw: 0, chairType: "Mesh Back", pros: ["Lightweight", "Eco focus"], cons: ["Limited reviews in English"], bestFor: "Sustainable EU office projects", seoTitle: "König+Neurath Teo Office Chair", seoDescription: "Teo mesh office chair specifications." }),
  // Interstuhl
  defineChair({ slug: "interstuhl-silver-262s", brand: "interstuhl", category: "office", name: "Interstuhl Silver 262S", nameEn: "Interstuhl Silver 262S", descriptionEn: "German task chair with Silver line ergonomics and robust build for daily intensive use.", priceUsd: 750, priceKrw: 0, chairType: "Task Chair", pros: ["German durability", "Good lumbar"], cons: ["EU-centric distribution"], bestFor: "German office standards", seoTitle: "Interstuhl Silver 262S Review", seoDescription: "Silver 262S ergonomic office chair specs." }),
  defineChair({ slug: "interstuhl-every-e3", brand: "interstuhl", category: "office", name: "Interstuhl Every E3", nameEn: "Interstuhl Every E3", descriptionEn: "Every line chair balancing price and ergonomics for large office rollouts.", priceUsd: 500, priceKrw: 0, chairType: "Task Chair", preset: "study", pros: ["Volume pricing", "Adequate ergonomics"], cons: ["Not premium tier"], bestFor: "Large EU office rollouts", seoTitle: "Interstuhl Every E3 Task Chair", seoDescription: "Every E3 specs for contract seating." }),
  defineChair({ slug: "interstuhl-pure-active", brand: "interstuhl", category: "office", name: "Interstuhl Pure Active", nameEn: "Interstuhl Pure Active", descriptionEn: "Active sitting chair encouraging movement with flexible seat and responsive back.", priceUsd: 800, priceKrw: 0, chairType: "Task Chair", pros: ["Movement encouragement", "Modern design"], cons: ["Unusual at first"], bestFor: "Active sitting advocates", seoTitle: "Interstuhl Pure Active Chair", seoDescription: "Pure Active movement seating overview." }),
  // Girsberger
  defineChair({ slug: "girsberger-enjoy", brand: "girsberger", category: "office", name: "Girsberger Enjoy", nameEn: "Girsberger Enjoy", descriptionEn: "Swiss task chair with precision mechanics and refined upholstery options.", priceUsd: 900, priceKrw: 0, chairType: "Task Chair", pros: ["Swiss precision", "Refined finish"], cons: ["Limited global presence"], bestFor: "Swiss and DACH offices", seoTitle: "Girsberger Enjoy Office Chair", seoDescription: "Enjoy task chair Swiss engineering specs." }),
  defineChair({ slug: "girsberger-impulse", brand: "girsberger", category: "office", name: "Girsberger Impulse", nameEn: "Girsberger Impulse", descriptionEn: "Dynamic task chair with flexible back and weight-activated recline.", priceUsd: 850, priceKrw: 0, chairType: "Task Chair", pros: ["Dynamic back", "Quality upholstery"], cons: ["Premium EU pricing"], bestFor: "European professional offices", seoTitle: "Girsberger Impulse Task Chair", seoDescription: "Impulse dynamic back specifications." }),
  defineChair({ slug: "girsberger-diagon", brand: "girsberger", category: "executive", name: "Girsberger Diagon", nameEn: "Girsberger Diagon", descriptionEn: "Executive chair with diagonal stitch detailing and high-back support for leadership spaces.", priceUsd: 1600, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Executive design", "Swiss quality"], cons: ["Expensive", "Heavy"], bestFor: "Executive offices in Switzerland", seoTitle: "Girsberger Diagon Executive Chair", seoDescription: "Diagon executive seating features." }),
  // Kastel
  defineChair({ slug: "kastel-kefir", brand: "kastel", category: "office", name: "Kastel Kefir", nameEn: "Kastel Kefir", descriptionEn: "Italian ergonomic task chair with synchronized mechanism and mesh back options.", priceUsd: 700, priceKrw: 0, chairType: "Mesh Back", pros: ["Italian design", "Good mechanism"], cons: ["Limited outside Italy"], bestFor: "Italian office projects", seoTitle: "Kastel Kefir Office Chair", seoDescription: "Kefir Italian ergonomic specs." }),
  defineChair({ slug: "kastel-kruna", brand: "kastel", category: "executive", name: "Kastel Kruna", nameEn: "Kastel Kruna", descriptionEn: "Italian executive chair with leather upholstery and aluminum base.", priceUsd: 1400, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Italian craftsmanship", "Executive look"], cons: ["EU distribution mainly"], bestFor: "Italian executive suites", seoTitle: "Kastel Kruna Executive Chair", seoDescription: "Kruna executive leather chair overview." }),
]
