import { defineChair } from "../helpers"
import type { HardcodedChair } from "../types"

export const GAMING_LUXURY_MISC_CHAIRS: HardcodedChair[] = [
  // Gaming
  defineChair({ slug: "secretlab-titan-evo-2022", brand: "secretlab", category: "gaming", name: "Secretlab Titan Evo 2022", nameEn: "Secretlab Titan Evo 2022", descriptionEn: "Premium gaming chair with cold-cure foam, magnetic headrest, and multi-tilt mechanism. Popular upgrade from budget racing chairs.", priceUsd: 519, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Excellent foam quality", "Strong recline", "Many size options"], cons: ["Still racing-style ergonomics", "Warm in summer"], bestFor: "Gamers upgrading from budget chairs", seoTitle: "Secretlab Titan Evo 2022 Review", seoDescription: "Titan Evo 2022 sizes, recline, and lumbar features." }),
  defineChair({ slug: "secretlab-omega", brand: "secretlab", category: "gaming", name: "Secretlab Omega", nameEn: "Secretlab Omega", descriptionEn: "Compact Secretlab model for smaller frames with same build quality as Titan line.", priceUsd: 449, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Fits smaller users", "Secretlab build"], cons: ["Discontinued/newer Evo preferred", "Narrow seat"], bestFor: "Smaller gamers under 175cm", seoTitle: "Secretlab Omega Gaming Chair", seoDescription: "Omega compact gaming chair specs." }),
  defineChair({ slug: "noblechairs-hero", brand: "noblechairs", category: "gaming", name: "Noblechairs Hero", nameEn: "noblechairs HERO", descriptionEn: "Real leather gaming chair with solid steel frame and understated design vs flashy racing chairs.", priceUsd: 549, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Real leather option", "Stable frame"], cons: ["Firm seat", "Heavy"], bestFor: "Gamers wanting leather and subtle design", seoTitle: "noblechairs HERO Review", seoDescription: "HERO leather gaming chair specifications." }),
  defineChair({ slug: "noblechairs-epic", brand: "noblechairs", category: "gaming", name: "Noblechairs Epic", nameEn: "noblechairs EPIC", descriptionEn: "Larger noblechairs model with wider seat and back for bigger gamers.", priceUsd: 499, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Wider than Hero", "Quality materials"], cons: ["Expensive for gaming category"], bestFor: "Larger gamers needing width", seoTitle: "noblechairs EPIC Gaming Chair", seoDescription: "EPIC wide gaming chair specs." }),
  defineChair({ slug: "andaseat-kaiser-3", brand: "andaseat", category: "gaming", name: "AndaSeat Kaiser 3", nameEn: "AndaSeat Kaiser 3", descriptionEn: "Large-format gaming chair with high-density foam and steel base rated for heavy users.", priceUsd: 429, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["High weight capacity", "Large sizing"], cons: ["Bulky", "Basic ergonomics vs task chairs"], bestFor: "Large gamers on a budget", seoTitle: "AndaSeat Kaiser 3 Review", seoDescription: "Kaiser 3 XL gaming chair weight capacity and specs." }),
  defineChair({ slug: "corsair-tc100-relaxed", brand: "corsair", category: "gaming", name: "Corsair TC100 Relaxed", nameEn: "Corsair TC100 Relaxed", descriptionEn: "Fabric gaming chair from Corsair with relaxed fit and breathable cloth vs PU leather.", priceUsd: 249, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Breathable fabric", "Affordable"], cons: ["Limited ergonomic adjustability"], bestFor: "Casual gamers and streamers", seoTitle: "Corsair TC100 Relaxed Gaming Chair", seoDescription: "TC100 Relaxed fabric gaming chair overview." }),
  defineChair({ slug: "razer-iskur-v2", brand: "razer", category: "gaming", name: "Razer Iskur V2", nameEn: "Razer Iskur V2", descriptionEn: "Gaming chair with built-in adjustable lumbar support and Razer branding for esports setups.", priceUsd: 399, priceKrw: 0, chairType: "Gaming", preset: "gaming", pros: ["Built-in lumbar dial", "Gaming aesthetic"], cons: ["Narrow for some users", "Not office-grade long-term"], bestFor: "Esports and Razer ecosystem fans", seoTitle: "Razer Iskur V2 Gaming Chair Review", seoDescription: "Iskur V2 lumbar system and gaming specs." }),
  // Executive / luxury
  defineChair({ slug: "poltrona-frau-dora", brand: "poltrona-frau", category: "executive", name: "Poltrona Frau Dora", nameEn: "Poltrona Frau Dora", descriptionEn: "Italian luxury executive seating with hand-finished leather and timeless design heritage.", priceUsd: 5000, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Luxury materials", "Design heritage"], cons: ["Extremely expensive", "Limited ergonomic adjust"], bestFor: "Luxury executive suites", seoTitle: "Poltrona Frau Dora Executive Chair", seoDescription: "Dora luxury Italian executive chair overview." }),
  defineChair({ slug: "walter-knoll-leadchair", brand: "walter-knoll", category: "executive", name: "Walter Knoll Leadchair", nameEn: "Walter Knoll Leadchair", descriptionEn: "German ultra-premium executive chair with refined leather and architectural presence.", priceUsd: 4500, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Ultra-premium build", "Architectural design"], cons: ["Very high price", "Heavy"], bestFor: "C-suite and design-architecture firms", seoTitle: "Walter Knoll Leadchair Executive", seoDescription: "Leadchair German luxury executive specifications." }),
  defineChair({ slug: "boss-design-mera", brand: "boss-design", category: "executive", name: "Boss Design Mera", nameEn: "Boss Design Mera", descriptionEn: "British executive chair with tailored upholstery and ergonomic adjustments for leadership spaces.", priceUsd: 2000, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["British craftsmanship", "Executive comfort"], cons: ["EU/UK focus"], bestFor: "UK corporate leadership offices", seoTitle: "Boss Design Mera Executive Chair", seoDescription: "Mera executive chair UK specs and features." }),
  // Study / value
  defineChair({ slug: "autonomous-ergochair-pro", brand: "autonomous", category: "study", name: "Autonomous ErgoChair Pro", nameEn: "Autonomous ErgoChair Pro", descriptionEn: "Direct-to-consumer ergonomic chair with adjustable lumbar, headrest, and mesh back at competitive pricing.", priceUsd: 499, priceKrw: 0, chairType: "Mesh Back", preset: "study", pros: ["Good feature set for price", "Headrest included"], cons: ["DTC support variability", "Below Herman Miller tier"], bestFor: "WFH buyers on a budget", seoTitle: "Autonomous ErgoChair Pro Review", seoDescription: "ErgoChair Pro specs, lumbar, and value comparison." }),
  defineChair({ slug: "flexispot-oc3", brand: "flexispot", category: "study", name: "FlexiSpot OC3", nameEn: "FlexiSpot OC3", descriptionEn: "Budget ergonomic chair often bundled with standing desks. Basic adjustments for starter home offices.", priceUsd: 199, priceKrw: 0, chairType: "Task Chair", preset: "study", pros: ["Very affordable", "Easy to buy online"], cons: ["Basic build", "Limited long-term durability"], bestFor: "Starter home offices with standing desks", seoTitle: "FlexiSpot OC3 Ergonomic Chair", seoDescription: "OC3 budget ergonomic chair overview." }),
  defineChair({ slug: "branch-ergonomic-chair", brand: "branch", category: "study", name: "Branch Ergonomic Chair", nameEn: "Branch Ergonomic Chair", descriptionEn: "WFH-focused task chair with seven adjustments and commercial-grade components at mid-market pricing.", priceUsd: 349, priceKrw: 0, chairType: "Task Chair", preset: "study", pros: ["Good WFH value", "Seven adjustments"], cons: ["Not true premium tier"], bestFor: "Remote workers and startups", seoTitle: "Branch Ergonomic Chair Review", seoDescription: "Branch ergonomic chair specs and WFH fit." }),
  // Standing / saddle
  defineChair({ slug: "varier-variable-balans", brand: "varier", category: "standing", name: "Varier Variable Balans", nameEn: "Varier Variable balans", descriptionEn: "Original kneeling chair promoting open hip angle and active sitting since the 1970s.", priceUsd: 395, priceKrw: 0, chairType: "Kneeling", preset: "standing", pros: ["Encourages active posture", "Compact"], cons: ["Knees need adaptation", "Not for all-day for everyone"], bestFor: "Active sitting and posture variation", seoTitle: "Varier Variable Balans Kneeling Chair", seoDescription: "Variable balans kneeling chair ergonomics." }),
  defineChair({ slug: "varier-thatsit-balans", brand: "varier", category: "standing", name: "Varier Thatsit Balans", nameEn: "Varier Thatsit balans", descriptionEn: "Kneeling chair with backrest support for users wanting kneeling benefits with more upper-back help.", priceUsd: 595, priceKrw: 0, chairType: "Kneeling", preset: "standing", pros: ["Backrest on kneeling design", "Quality build"], cons: ["Niche posture"], bestFor: "Users transitioning to active sitting", seoTitle: "Varier Thatsit Balans Review", seoDescription: "Thatsit balans kneeling chair with backrest specs." }),
  defineChair({ slug: "salli-saddle-swing", brand: "salli", category: "standing", name: "Saddle Salli Swing", nameEn: "Salli SwingFit", descriptionEn: "Split saddle seat reduces perineal pressure and supports dental, medical, and sit-stand workflows.", priceUsd: 1100, priceKrw: 0, chairType: "Saddle", preset: "standing", pros: ["Split saddle health benefits", "Sit-stand friendly"], cons: ["Requires adaptation period", "Not traditional sitting"], bestFor: "Dental, medical, and sit-stand users", seoTitle: "Salli SwingFit Saddle Chair", seoDescription: "Salli split saddle chair specs and health benefits." }),
  defineChair({ slug: "bambach-saddle-seat", brand: "bambach", category: "standing", name: "Bambach Saddle Seat", nameEn: "Bambach Saddle Seat", descriptionEn: "Australian saddle seat promoting natural spinal curves for healthcare and industrial workstations.", priceUsd: 900, priceKrw: 0, chairType: "Saddle", preset: "standing", pros: ["Healthcare provenance", "Posture support"], cons: ["Unusual for office workers", "Premium for category"], bestFor: "Healthcare and industrial ergonomic needs", seoTitle: "Bambach Saddle Seat Review", seoDescription: "Bambach saddle seat ergonomic specifications." }),
]
