import { defineChair } from "../helpers"
import type { HardcodedChair } from "../types"

export const HERMAN_MILLER_CHAIRS: HardcodedChair[] = [
  defineChair({
    slug: "herman-miller-aeron-b",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Aeron B",
    nameEn: "Herman Miller Aeron (Size B)",
    descriptionEn:
      "Iconic Pellicle mesh task chair sized for medium builds. PostureFit SL lumbar and 8Z pellicle zones deliver exceptional ventilation for all-day desk work.",
    priceUsd: 1395,
    priceKrw: 2630000,
    chairType: "Mesh Back",
    pros: ["Industry-leading lumbar support", "Excellent breathability", "12-year warranty"],
    cons: ["Premium price", "Mesh seat takes adjustment"],
    bestFor: "Medium-height professionals sitting 8+ hours daily",
    seoTitle: "Herman Miller Aeron Size B Review & Specs",
    seoDescription: "Aeron Size B specs, lumbar support, seat height range, and ergonomic ratings for medium-build office workers.",
    chairSpecs: { recommendedHeightMin: 165, recommendedHeightMax: 180, seatHeightMin: 40, seatHeightMax: 57, weightCapacityKg: 159 },
  }),
  defineChair({
    slug: "herman-miller-aeron-c",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Aeron C",
    nameEn: "Herman Miller Aeron (Size C)",
    descriptionEn:
      "Largest Aeron size with wider seat and reinforced tilt for taller or heavier users. Same Pellicle mesh and PostureFit SL as other Aeron sizes.",
    priceUsd: 1495,
    priceKrw: 2780000,
    chairType: "Mesh Back",
    pros: ["Sized for tall users", "Strong tilt mechanism", "Durable mesh"],
    cons: ["Too large for petite users", "High cost"],
    bestFor: "Tall users 180cm+ or heavier builds",
    seoTitle: "Herman Miller Aeron Size C — Tall User Specs",
    seoDescription: "Aeron Size C dimensions, weight capacity, and ergonomic fit guide for tall office workers.",
    chairSpecs: { recommendedHeightMin: 175, recommendedHeightMax: 198, seatWidth: 54, seatDepth: 47, weightCapacityKg: 159 },
  }),
  defineChair({
    slug: "herman-miller-embody",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Embody",
    nameEn: "Herman Miller Embody",
    descriptionEn:
      "Pixelated support matrix adapts to micro-movements and distributes pressure evenly. Designed with physicians for long coding and design sessions.",
    priceUsd: 1795,
    priceKrw: 3000000,
    chairType: "Task Chair",
    preset: "premium_task",
    pros: ["Dynamic back support", "Reduces pressure points", "Highly adjustable"],
    cons: ["Very expensive", "Heavy chair"],
    bestFor: "Developers and designers with long sitting hours",
    seoTitle: "Herman Miller Embody Review & Ergonomic Specs",
    seoDescription: "Embody chair specs, back support technology, and fit guide for intensive computer work.",
    chairSpecs: { hasHeadrest: false, reclineRange: 130, chairWeightKg: 24 },
  }),
  defineChair({
    slug: "herman-miller-cosm-high-back",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Cosm High Back",
    nameEn: "Herman Miller Cosm High Back",
    descriptionEn:
      "Auto-harmonic tilt requires minimal manual adjustment. Intercept suspension mesh and high back suit modern open offices.",
    priceUsd: 1395,
    priceKrw: 0,
    chairType: "Mesh Back",
    pros: ["Auto-adjusting tilt", "Sleek design", "Minimal knobs"],
    cons: ["Limited fine-tuning", "Headrest on high back only"],
    bestFor: "Hot-desking and shared workspaces",
    seoTitle: "Herman Miller Cosm High Back Specs",
    seoDescription: "Cosm High Back auto-tilt, mesh support, and ergonomic features for modern offices.",
    chairSpecs: { hasHeadrest: true, armrestType: "2D", reclineRange: 135 },
  }),
  defineChair({
    slug: "herman-miller-cosm-low-back",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Cosm Low Back",
    nameEn: "Herman Miller Cosm Low Back",
    descriptionEn:
      "Low-back Cosm variant with automatic recline and flexible frame. Ideal for users who prefer an open, upright posture.",
    priceUsd: 1195,
    priceKrw: 0,
    chairType: "Mesh Back",
    pros: ["Clean aesthetic", "Auto recline", "Light adjustment"],
    cons: ["No headrest", "Less upper-back support"],
    bestFor: "Active sitters and collaborative spaces",
    seoTitle: "Herman Miller Cosm Low Back Review",
    seoDescription: "Cosm Low Back specifications and fit guide for upright office seating.",
    chairSpecs: { hasHeadrest: false, backrestHeight: 42 },
  }),
  defineChair({
    slug: "herman-miller-sayl",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Sayl",
    nameEn: "Herman Miller Sayl",
    descriptionEn:
      "Y-Tower suspension back reduces material use while maintaining ergonomic support. Affordable entry to Herman Miller ergonomics.",
    priceUsd: 595,
    priceKrw: 0,
    chairType: "Mesh Back",
    preset: "study",
    pros: ["Distinctive design", "Good value for brand", "Compact footprint"],
    cons: ["Limited padding", "Basic armrests on base models"],
    bestFor: "Home offices and startups on a budget",
    seoTitle: "Herman Miller Sayl — Affordable Ergonomic Chair",
    seoDescription: "Sayl chair specs, Y-Tower back support, and value comparison for home office buyers.",
    chairSpecs: { armrestType: "2D", warrantyYears: 12 },
  }),
  defineChair({
    slug: "herman-miller-mirra-2",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Mirra 2",
    nameEn: "Herman Miller Mirra 2",
    descriptionEn:
      "TriFlex polymer back and AireWeave suspension seat balance support and breathability. Highly configurable at a lower price than Aeron.",
    priceUsd: 1045,
    priceKrw: 0,
    chairType: "Task Chair",
    pros: ["Strong adjustability", "Responsive back", "Good warranty"],
    cons: ["Less premium feel than Aeron", "Arm pads wear over time"],
    bestFor: "Teams needing many configurable task chairs",
    seoTitle: "Herman Miller Mirra 2 Specs & Review",
    seoDescription: "Mirra 2 adjustability, TriFlex back, and ergonomic comparison vs Aeron.",
    chairSpecs: { seatHeightMin: 38, seatHeightMax: 55 },
  }),
  defineChair({
    slug: "herman-miller-lino",
    brand: "herman-miller",
    category: "office",
    name: "Herman Miller Lino",
    nameEn: "Herman Miller Lino",
    descriptionEn:
      "Sustainable task chair with 2.5D suspension back and optional headrest. Designed for everyday office comfort at accessible pricing.",
    priceUsd: 825,
    priceKrw: 0,
    chairType: "Task Chair",
    preset: "premium_task",
    pros: ["Eco-conscious materials", "Comfortable for long sits", "Optional headrest"],
    cons: ["Fewer adjustments than Aeron", "Limited color options"],
    bestFor: "Eco-minded offices and everyday task work",
    seoTitle: "Herman Miller Lino Office Chair Specs",
    seoDescription: "Lino sustainable task chair features, specs, and ergonomic overview.",
    chairSpecs: { hasHeadrest: true, warrantyYears: 12 },
  }),
  defineChair({
    slug: "herman-miller-embody-gaming",
    brand: "herman-miller",
    category: "gaming",
    name: "Herman Miller x Logitech Embody Gaming",
    nameEn: "Herman Miller x Logitech G Embody Gaming Chair",
    descriptionEn:
      "Embody platform tuned for gamers with cooling foam, copper-infused foam, and Logitech G colorways. Same pixelated back as office Embody.",
    priceUsd: 1795,
    priceKrw: 0,
    chairType: "Gaming",
    preset: "gaming",
    pros: ["Office-grade ergonomics", "Cooling foam layer", "Premium build"],
    cons: ["No racing aesthetic", "Very expensive for gaming"],
    bestFor: "Serious gamers prioritizing spine health over looks",
    seoTitle: "Herman Miller Embody Gaming Chair Review",
    seoDescription: "Logitech G Embody gaming specs, cooling features, and ergonomic benefits.",
    chairSpecs: { reclineRange: 135, warrantyYears: 12 },
  }),
]
