import { defineChair } from "../helpers"
import type { HardcodedChair } from "../types"

export const JAPAN_KOREA_CHAIRS: HardcodedChair[] = [
  // Okamura
  defineChair({ slug: "okamura-contessa-ii", brand: "okamura", category: "executive", name: "Okamura Contessa II", nameEn: "Okamura Contessa II", descriptionEn: "Japanese flagship executive chair with precision adjustment, high-density foam, and polished aluminum frame.", priceUsd: 2200, priceKrw: 2310000, chairType: "Executive", preset: "executive", pros: ["Exceptional build quality", "Smooth adjustments", "Executive aesthetics"], cons: ["Very expensive", "Heavy"], bestFor: "Executive offices in Japan and Asia", seoTitle: "Okamura Contessa II Executive Chair", seoDescription: "Contessa II specs, lumbar, and executive seating overview." }),
  defineChair({ slug: "okamura-sylphy", brand: "okamura", category: "office", name: "Okamura Sylphy", nameEn: "Okamura Sylphy", descriptionEn: "Dual-back mesh adapts to different torso shapes with a slim profile. Popular in compact Japanese offices.", priceUsd: 1200, priceKrw: 1680000, chairType: "Mesh Back", pros: ["Adaptive dual back", "Compact footprint", "Strong ventilation"], cons: ["Firm seat for some users", "Premium in Korea"], bestFor: "Compact offices and smaller frames", seoTitle: "Okamura Sylphy Office Chair Specs", seoDescription: "Sylphy dual-back mesh, dimensions, and ergonomic fit." }),
  defineChair({ slug: "okamura-legno", brand: "okamura", category: "executive", name: "Okamura Legno", nameEn: "Okamura Legno", descriptionEn: "Wood-accented executive chair combining warmth of timber with Okamura ergonomic engineering.", priceUsd: 2500, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Premium materials", "Executive presence", "Comfortable padding"], cons: ["Heavy", "Limited mesh breathability"], bestFor: "Executive suites and law offices", seoTitle: "Okamura Legno Executive Chair", seoDescription: "Legno executive chair materials and ergonomic features." }),
  defineChair({ slug: "okamura-baron", brand: "okamura", category: "office", name: "Okamura Baron", nameEn: "Okamura Baron", descriptionEn: "Mid-range Okamura task chair with adjustable lumbar and synchro-tilt for daily office work.", priceUsd: 750, priceKrw: 0, chairType: "Task Chair", pros: ["Reliable Japanese quality", "Good lumbar"], cons: ["Less known globally", "Fewer reviews in English"], bestFor: "Japanese corporate standard seating", seoTitle: "Okamura Baron Task Chair", seoDescription: "Baron office chair specs and ergonomic overview." }),
  defineChair({ slug: "okamura-sabrina", brand: "okamura", category: "office", name: "Okamura Sabrina", nameEn: "Okamura Sabrina", descriptionEn: "Mesh task chair with flexible frame and adjustable headrest option for long computer sessions.", priceUsd: 900, priceKrw: 0, chairType: "Mesh Back", pros: ["Breathable mesh", "Optional headrest", "Light frame"], cons: ["Armrests vary by trim"], bestFor: "General office task work", seoTitle: "Okamura Sabrina Mesh Chair Specs", seoDescription: "Sabrina mesh back, headrest options, and fit guide." }),
  defineChair({ slug: "okamura-portone", brand: "okamura", category: "executive", name: "Okamura Portone", nameEn: "Okamura Portone", descriptionEn: "High-back executive model with generous cushioning and polished base for leadership offices.", priceUsd: 1800, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Luxurious padding", "High back support"], cons: ["Runs warm in summer", "Large footprint"], bestFor: "C-suite and private offices", seoTitle: "Okamura Portone Executive Chair", seoDescription: "Portone executive specs and comfort features." }),
  defineChair({ slug: "okamura-cronos", brand: "okamura", category: "office", name: "Okamura Cronos", nameEn: "Okamura Cronos", descriptionEn: "Ergonomic task chair with multi-adjustment arms and seat depth for diverse office populations.", priceUsd: 850, priceKrw: 0, chairType: "Task Chair", pros: ["Seat depth slider", "Solid warranty in Japan"], cons: ["Limited availability outside Asia"], bestFor: "Large Japanese office deployments", seoTitle: "Okamura Cronos Office Chair", seoDescription: "Cronos adjustability and ergonomic specifications." }),
  // Kokuyo
  defineChair({ slug: "kokuyo-ing", brand: "kokuyo", category: "office", name: "Kokuyo Ing", nameEn: "Kokuyo Ing", descriptionEn: "Popular Korean-market ergonomic chair with wide seat and strong local service network via Chairpark.", priceUsd: 650, priceKrw: 2350000, chairType: "Task Chair", pros: ["Easy service in Korea", "Comfortable seat", "Good value locally"], cons: ["Less known internationally", "Fabric options limited"], bestFor: "Korean offices and WFH buyers", seoTitle: "Kokuyo Ing Chair — Korea Specs & Price", seoDescription: "Ing chair Korean pricing, specs, and ergonomic review." }),
  defineChair({ slug: "kokuyo-ing-cloud", brand: "kokuyo", category: "office", name: "Kokuyo Ing Cloud", nameEn: "Kokuyo Ing Cloud", descriptionEn: "Mesh variant of Ing line with improved ventilation for long meetings and hybrid work.", priceUsd: 750, priceKrw: 3450000, chairType: "Mesh Back", pros: ["Better cooling than Ing", "Hybrid-work friendly", "Korean support"], cons: ["Premium over Ing", "Mesh firmness"], bestFor: "Long meetings and hybrid work in Korea", seoTitle: "Kokuyo Ing Cloud Mesh Chair", seoDescription: "Ing Cloud mesh specs and comparison to standard Ing." }),
  defineChair({ slug: "kokuyo-crg", brand: "kokuyo", category: "office", name: "Kokuyo CRG", nameEn: "Kokuyo CRG", descriptionEn: "Compact ergonomic task chair designed for smaller Asian body types and dense office layouts.", priceUsd: 500, priceKrw: 1200000, chairType: "Task Chair", preset: "study", pros: ["Compact size", "Affordable in Korea"], cons: ["Limited for tall users"], bestFor: "Smaller frames and tight workspaces", seoTitle: "Kokuyo CRG Compact Office Chair", seoDescription: "CRG compact ergonomic specs for Asian office fit." }),
  defineChair({ slug: "kokuyo-duora", brand: "kokuyo", category: "office", name: "Kokuyo Duora", nameEn: "Kokuyo Duora", descriptionEn: "Dual-structure back supports both upright task work and relaxed recline with minimal adjustment.", priceUsd: 900, priceKrw: 0, chairType: "Task Chair", pros: ["Versatile postures", "Modern design"], cons: ["Learning curve on adjustments"], bestFor: "Agile teams and creative offices", seoTitle: "Kokuyo Duora Ergonomic Chair", seoDescription: "Duora dual-back support and office use cases." }),
  // Itoki
  defineChair({ slug: "itoki-act2", brand: "itoki", category: "office", name: "Itoki ACT2", nameEn: "Itoki ACT2", descriptionEn: "Japanese active-sitting chair encouraging micro-movement with flexible seat and responsive back.", priceUsd: 600, priceKrw: 0, chairType: "Task Chair", pros: ["Encourages movement", "Affordable in Japan"], cons: ["Unusual feel at first", "Not for static sitters"], bestFor: "Active sitting and affordable ergonomics", seoTitle: "Itoki ACT2 Active Sitting Chair", seoDescription: "ACT2 active sitting mechanism and ergonomic benefits." }),
  defineChair({ slug: "itoki-leala", brand: "itoki", category: "office", name: "Itoki Leala", nameEn: "Itoki Leala", descriptionEn: "Mesh office chair with clean lines and adjustable lumbar for standard Japanese office deployments.", priceUsd: 700, priceKrw: 0, chairType: "Mesh Back", pros: ["Lightweight mesh", "Good ventilation"], cons: ["Basic armrests on entry trim"], bestFor: "Standard Japanese office seating", seoTitle: "Itoki Leala Mesh Office Chair", seoDescription: "Leala mesh specs and office fit guide." }),
  defineChair({ slug: "itoki-spina", brand: "itoki", category: "office", name: "Itoki Spina", nameEn: "Itoki Spina", descriptionEn: "Spinal-alignment focused task chair with split back panels for independent thoracic and lumbar support.", priceUsd: 850, priceKrw: 0, chairType: "Task Chair", pros: ["Split back design", "Targeted lumbar"], cons: ["Niche fit preference"], bestFor: "Users with specific back support needs", seoTitle: "Itoki Spina Split-Back Chair", seoDescription: "Spina split-back ergonomic technology and specs." }),
  defineChair({ slug: "itoki-karuga", brand: "itoki", category: "executive", name: "Itoki Karuga", nameEn: "Itoki Karuga", descriptionEn: "Executive mesh chair with aluminum base and generous adjustments for management offices.", priceUsd: 1100, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Executive look", "Mesh breathability"], cons: ["Premium pricing in Japan"], bestFor: "Management offices in Japan", seoTitle: "Itoki Karuga Executive Mesh Chair", seoDescription: "Karuga executive mesh specs and features." }),
  // Uchida
  defineChair({ slug: "uchida-finora", brand: "uchida", category: "office", name: "Uchida Finora", nameEn: "Uchida Finora", descriptionEn: "Japanese task chair with synchro mechanism and adjustable arms for corporate office standards.", priceUsd: 650, priceKrw: 0, chairType: "Task Chair", pros: ["Corporate-grade durability", "Clean design"], cons: ["Limited global distribution"], bestFor: "Japanese corporate offices", seoTitle: "Uchida Finora Office Chair", seoDescription: "Finora task chair specifications." }),
  defineChair({ slug: "uchida-viella", brand: "uchida", category: "executive", name: "Uchida Viella", nameEn: "Uchida Viella", descriptionEn: "High-back executive chair with leather options and polished aluminum for leadership floors.", priceUsd: 1400, priceKrw: 0, chairType: "Executive", preset: "executive", pros: ["Executive upholstery", "Stable base"], cons: ["Heavy", "Warm in summer"], bestFor: "Executive floors in Japan", seoTitle: "Uchida Viella Executive Chair", seoDescription: "Viella executive chair specs and materials." }),
  // Sidiz
  defineChair({ slug: "sidiz-t50", brand: "sidiz", category: "study", name: "Sidiz T50", nameEn: "Sidiz T50", descriptionEn: "Popular Korean ergonomic chair with headrest and adjustable lumbar at mid-range pricing. Strong domestic reviews.", priceUsd: 350, priceKrw: 450000, chairType: "Task Chair", preset: "study", pros: ["Great value in Korea", "Headrest included", "Easy to buy locally"], cons: ["Build tier below Herman Miller", "Armrests basic"], bestFor: "Students and home office in Korea", seoTitle: "Sidiz T50 Review — Korean Ergonomic Chair", seoDescription: "T50 specs, Korean price, and ergonomic overview." }),
  defineChair({ slug: "sidiz-t80", brand: "sidiz", category: "office", name: "Sidiz T80", nameEn: "Sidiz T80", descriptionEn: "Upgraded Sidiz line with improved mechanism and mesh options for full-time office workers.", priceUsd: 550, priceKrw: 750000, chairType: "Mesh Back", pros: ["Better than T50 for daily use", "Mesh option", "Korean warranty"], cons: ["Still below premium imports"], bestFor: "Full-time desk workers in Korea", seoTitle: "Sidiz T80 Office Chair Specs", seoDescription: "T80 vs T50 comparison and ergonomic specs." }),
]
