import { defineChair } from "../helpers"
import type { HardcodedChair } from "../types"

export const STEELCASE_CHAIRS: HardcodedChair[] = [
  defineChair({
    slug: "steelcase-leap-v2",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Leap V2",
    nameEn: "Steelcase Leap V2",
    descriptionEn:
      "LiveBack technology mimics spine movement; Natural Glide recline keeps eyes aligned with screen. One of the most researched task chairs ever made.",
    priceUsd: 1099,
    priceKrw: 2050000,
    chairType: "Task Chair",
    pros: ["Excellent lumbar", "Durable build", "Wide adjustment range"],
    cons: ["Bulky silhouette", "Fabric can wear"],
    bestFor: "All-day office workers needing proven ergonomics",
    seoTitle: "Steelcase Leap V2 Review & Specs",
    seoDescription: "Leap V2 LiveBack, seat depth, and ergonomic ratings for daily office use.",
    chairSpecs: { seatDepth: 48, reclineRange: 120 },
  }),
  defineChair({
    slug: "steelcase-gesture",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Gesture",
    nameEn: "Steelcase Gesture",
    descriptionEn:
      "360-degree arms follow device use from keyboard to tablet. Core interface mimics spine for multi-posture work.",
    priceUsd: 1299,
    priceKrw: 2350000,
    chairType: "Task Chair",
    pros: ["Best-in-class armrests", "Great for multi-device work", "Smooth recline"],
    cons: ["Expensive", "Seat can feel firm"],
    bestFor: "Dual-monitor and tablet-heavy workflows",
    seoTitle: "Steelcase Gesture Chair — Armrest & Specs",
    seoDescription: "Gesture 360 armrests, lumbar support, and fit guide for modern desk setups.",
    chairSpecs: { armrestType: "4D", seatWidth: 51 },
  }),
  defineChair({
    slug: "steelcase-think-v2",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Think V2",
    nameEn: "Steelcase Think V2",
    descriptionEn:
      "Weight-activated mechanism and back flexors adapt without manual tuning. Sustainable design with up to 28% recycled content.",
    priceUsd: 899,
    priceKrw: 0,
    chairType: "Task Chair",
    pros: ["Intuitive auto-adjust", "Sustainable materials", "Compact back"],
    cons: ["Less premium than Leap", "Limited headrest options"],
    bestFor: "Sustainability-focused offices",
    seoTitle: "Steelcase Think V2 Ergonomic Specs",
    seoDescription: "Think V2 auto-adjust mechanism, recycled materials, and office fit guide.",
  }),
  defineChair({
    slug: "steelcase-amia",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Amia",
    nameEn: "Steelcase Amia",
    descriptionEn:
      "LiveLumbar moves with your back; affordable Steelcase entry with solid build quality and 4-way arms on higher trims.",
    priceUsd: 649,
    priceKrw: 0,
    chairType: "Task Chair",
    preset: "premium_task",
    pros: ["Good value", "LiveLumbar support", "Steelcase durability"],
    cons: ["Basic aesthetics", "Fewer features than Leap"],
    bestFor: "Budget-conscious ergonomic buyers",
    seoTitle: "Steelcase Amia Office Chair Review",
    seoDescription: "Amia LiveLumbar specs, price, and comparison to Leap V2.",
  }),
  defineChair({
    slug: "steelcase-series-1",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Series 1",
    nameEn: "Steelcase Series 1",
    descriptionEn:
      "Lightweight task chair with 3D LiveBack and adjustable lumbar. Designed for agile teams and home offices.",
    priceUsd: 499,
    priceKrw: 0,
    chairType: "Task Chair",
    preset: "study",
    pros: ["Affordable Steelcase", "Easy assembly", "Decent lumbar"],
    cons: ["Plastic components", "Not for heavy daily use"],
    bestFor: "Home offices and secondary desks",
    seoTitle: "Steelcase Series 1 Specs & Price",
    seoDescription: "Series 1 task chair dimensions, lumbar, and value overview.",
    chairSpecs: { warrantyYears: 12 },
  }),
  defineChair({
    slug: "steelcase-series-2",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Series 2",
    nameEn: "Steelcase Series 2",
    descriptionEn:
      "Upgraded Series line with more padding and adjustment than Series 1. Air LiveBack and optional headrest.",
    priceUsd: 699,
    priceKrw: 0,
    chairType: "Task Chair",
    preset: "study",
    pros: ["Better padding than Series 1", "Optional headrest", "Good warranty"],
    cons: ["Still below Leap tier", "Limited seat depth range"],
    bestFor: "Growing teams needing scalable seating",
    seoTitle: "Steelcase Series 2 Office Chair",
    seoDescription: "Series 2 vs Series 1 comparison, specs, and ergonomic features.",
  }),
  defineChair({
    slug: "steelcase-karman",
    brand: "steelcase",
    category: "office",
    name: "Steelcase Karman",
    nameEn: "Steelcase Karman",
    descriptionEn:
      "Ultralight performance chair under 5 kg with interwoven suspension. Targets high-mobility knowledge workers.",
    priceUsd: 1199,
    priceKrw: 0,
    chairType: "Mesh Back",
    pros: ["Extremely light", "Modern aesthetic", "Responsive flex"],
    cons: ["Newer model, less long-term data", "Premium pricing"],
    bestFor: "Design-forward offices and mobile workers",
    seoTitle: "Steelcase Karman Lightweight Chair Specs",
    seoDescription: "Karman ultralight frame, suspension, and ergonomic design overview.",
    chairSpecs: { chairWeightKg: 5, hasLumbarSupport: true },
  }),
  defineChair({
    slug: "steelcase-coalesse-sw1",
    brand: "steelcase",
    category: "lounge",
    name: "Steelcase Coalesse SW_1",
    nameEn: "Steelcase Coalesse SW_1",
    descriptionEn:
      "Lounge seating from Coalesse with soft curves for informal collaboration. Lower seat height and relaxed recline.",
    priceUsd: 2500,
    priceKrw: 0,
    chairType: "Lounge",
    preset: "lounge",
    pros: ["Statement design", "Comfortable lounge posture", "Premium upholstery"],
    cons: ["Not a task chair", "Very expensive"],
    bestFor: "Executive lounges and collaboration zones",
    seoTitle: "Steelcase Coalesse SW_1 Lounge Chair",
    seoDescription: "Coalesse SW_1 lounge seating specs and workplace use cases.",
  }),
  defineChair({
    slug: "steelcase-respawn-gaming",
    brand: "steelcase",
    category: "gaming",
    name: "Steelcase x Respawn Gaming Chair",
    nameEn: "Steelcase Respawn Gaming Chair",
    descriptionEn:
      "Steelcase ergonomics applied to gaming aesthetics with adjustable lumbar and recline. Licensed Respawn collaboration.",
    priceUsd: 499,
    priceKrw: 0,
    chairType: "Gaming",
    preset: "gaming",
    pros: ["Steelcase backing", "Gaming recline", "Affordable vs Embody Gaming"],
    cons: ["Still racing-style limitations", "Less breathable than mesh task chairs"],
    bestFor: "Gamers wanting Steelcase ergonomics",
    seoTitle: "Steelcase Respawn Gaming Chair Review",
    seoDescription: "Steelcase Respawn gaming chair specs, recline, and lumbar support.",
  }),
  defineChair({
    slug: "steelcase-coalesse-exponents",
    brand: "steelcase",
    category: "conference",
    name: "Steelcase Coalesse Exponents",
    nameEn: "Steelcase Coalesse Exponents",
    descriptionEn:
      "Conference chair with refined upholstery for meeting rooms. Swivel base and moderate recline for short sessions.",
    priceUsd: 1800,
    priceKrw: 0,
    chairType: "Conference",
    preset: "conference",
    pros: ["Meeting-room appropriate", "Premium materials", "Compact arm options"],
    cons: ["Not for all-day desk work", "Limited ergonomic tuning"],
    bestFor: "Executive conference rooms",
    seoTitle: "Steelcase Coalesse Exponents Conference Chair",
    seoDescription: "Exponents conference chair specs for meeting and boardroom spaces.",
  }),
]
