import type { Metadata } from "next";
import Link from "next/link";
import { cache } from "react";
import { notFound } from "next/navigation";
import { getPublicStores, getStoreCatalog, enrichStore } from "@/lib/showrooms/server";
import { trialPages } from "@/lib/showrooms/trial-pages";
import { countryPath } from "@/lib/showrooms/locations";
import { SITE_URL } from "@/lib/site-config";
import "@/app/stores/locations/[[...place]]/locations.css";

export const revalidate = 300;
export function generateStaticParams() { return []; }
const load = cache(async (product:string, city:string) => { if(process.env.SHOWROOMS_ENABLED!=="true")notFound(); const [result,catalog]=await Promise.all([getPublicStores(),getStoreCatalog()]); if(result.unavailable)throw new Error("Store directory temporarily unavailable"); const page=trialPages(result.stores.map(s=>enrichStore(s,catalog))).find(p=>p.productSlug===product&&p.cityKey===city); if(!page)notFound(); return page; });
type Props={params:Promise<{product:string;city:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const p=await params,r=await load(p.product,p.city),title=`Where to Try ${r.productName} in ${r.cityName}`,description=`Find source-confirmed places to try ${r.productName} in ${r.cityName}, ${r.countryName}. Check addresses, appointments and availability before visiting.`;return{title,description,alternates:{canonical:r.path},openGraph:{title,description,url:r.path,type:"website"},robots:{index:true,follow:true}};}
export default async function TrialPageRoute({params}:Props){const p=await params,r=await load(p.product,p.city);const schema={"@context":"https://schema.org","@type":"CollectionPage","@id":SITE_URL+r.path,url:SITE_URL+r.path,name:`Where to try ${r.productName} in ${r.cityName}`,inLanguage:"en",mainEntity:{"@type":"ItemList",numberOfItems:r.stores.length,itemListElement:r.stores.map((s,i)=>({"@type":"ListItem",position:i+1,name:s.name,url:`${SITE_URL}/stores/${s.slug}`}))}};return <main className="store-locations"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><header className="location-header"><Link href="/" className="location-logo">Chairpedia</Link><Link href="/stores">Explore the map ↗</Link></header><div className="location-wrap"><nav className="location-crumbs" aria-label="Breadcrumb"><Link href="/stores">Find stores</Link> / <Link href={countryPath(r.countryCode)}>{r.countryName}</Link> / <span>{r.productName}</span></nav><section className="location-hero"><p className="location-eyebrow">SOURCE-CONFIRMED CHAIR TRIALS</p><h1>Where to try {r.productName} in {r.cityName}</h1><p>{r.stores.length} {r.stores.length===1?"location lists":"locations list"} this model as available to try. Contact the store before travelling because configurations, stock and access can change.</p><div className="location-card-actions"><Link href={`/products/${r.productSlug}`}>Research {r.productName} →</Link><Link href="/compare">Compare chair models →</Link></div></section><section><h2>Places to try this chair</h2><div className="location-store-grid">{r.stores.map(s=><article className="location-store-card" key={s.id}><p className="location-eyebrow">{s.city} · CONFIRMED MODEL</p><h3><Link href={`/stores/${s.slug}`}>{s.name}</Link></h3><p>{[s.address,s.unit].filter(Boolean).join(", ")}</p><p><strong>{s.appointment==="required"?"Appointment required":s.appointment==="walk_in"?"Walk-ins welcome":"Contact before visiting"}</strong></p><div className="location-card-actions"><Link href={`/stores/${s.slug}`}>Visit details →</Link><a href={s.source_url} target="_blank" rel="noopener noreferrer">Verification source ↗</a></div></article>)}</div></section><section className="location-advice"><h2>Before visiting</h2><p>Ask the store to confirm the exact size, upholstery and options you want to test. A source-confirmed model may still be sold, moved or temporarily unavailable after the latest check.</p><p><Link href={`/products/${r.productSlug}`}>Read specifications and reviews</Link> before your visit, then compare seat fit, controls and warranty terms in person.</p></section></div></main>}
