import type { BrandRow } from "./types"

/** All brands referenced by ALL_CHAIRS — upserted before products */
export const ALL_BRANDS: BrandRow[] = [
  { slug: "herman-miller", name: "Herman Miller", country: "US", tier: "ultra_premium", founded_year: 1905 },
  { slug: "steelcase", name: "Steelcase", country: "US", tier: "premium", founded_year: 1912 },
  { slug: "okamura", name: "Okamura", country: "JP", tier: "premium", founded_year: 1945 },
  { slug: "humanscale", name: "Humanscale", country: "US", tier: "premium", founded_year: 1983 },
  { slug: "hag-flokk", name: "HÅG / Flokk", country: "NO", tier: "premium", founded_year: 1943 },
  { slug: "wilkhahn", name: "Wilkhahn", country: "DE", tier: "premium", founded_year: 1907 },
  { slug: "vitra", name: "Vitra", country: "CH", tier: "premium", founded_year: 1950 },
  { slug: "knoll", name: "Knoll", country: "US", tier: "premium", founded_year: 1938 },
  { slug: "haworth", name: "Haworth", country: "US", tier: "premium", founded_year: 1948 },
  { slug: "sedus", name: "Sedus", country: "DE", tier: "premium", founded_year: 1926 },
  { slug: "kokuyo", name: "Kokuyo", country: "JP", tier: "premium", founded_year: 1871 },
  { slug: "itoki", name: "Itoki", country: "JP", tier: "premium", founded_year: 1890 },
  { slug: "uchida", name: "Uchida", country: "JP", tier: "premium", founded_year: 1910 },
  { slug: "global", name: "Global Furniture Group", country: "CA", tier: "premium", founded_year: 1966 },
  { slug: "konig-neurath", name: "König+Neurath", country: "DE", tier: "premium", founded_year: 1888 },
  { slug: "interstuhl", name: "Interstuhl", country: "DE", tier: "premium", founded_year: 1961 },
  { slug: "girsberger", name: "Girsberger", country: "CH", tier: "premium", founded_year: 1889 },
  { slug: "kastel", name: "Kastel", country: "IT", tier: "premium", founded_year: 1987 },
  { slug: "poltrona-frau", name: "Poltrona Frau", country: "IT", tier: "ultra_premium", founded_year: 1912 },
  { slug: "walter-knoll", name: "Walter Knoll", country: "DE", tier: "ultra_premium", founded_year: 1865 },
  { slug: "boss-design", name: "Boss Design", country: "GB", tier: "premium", founded_year: 1983 },
  { slug: "secretlab", name: "Secretlab", country: "SG", tier: "mid_range", founded_year: 2014 },
  { slug: "noblechairs", name: "Noblechairs", country: "AT", tier: "mid_range", founded_year: 2015 },
  { slug: "andaseat", name: "AndaSeat", country: "CN", tier: "mid_range", founded_year: 2012 },
  { slug: "corsair", name: "Corsair", country: "US", tier: "mid_range", founded_year: 1994 },
  { slug: "razer", name: "Razer", country: "SG", tier: "mid_range", founded_year: 2005 },
  { slug: "autonomous", name: "Autonomous", country: "US", tier: "mid_range", founded_year: 2015 },
  { slug: "flexispot", name: "FlexiSpot", country: "CN", tier: "mid_range", founded_year: 2013 },
  { slug: "branch", name: "Branch", country: "US", tier: "mid_range", founded_year: 2019 },
  { slug: "sidiz", name: "Sidiz", country: "KR", tier: "mid_range", founded_year: 1992 },
  { slug: "varier", name: "Varier", country: "NO", tier: "premium", founded_year: 1979 },
  { slug: "salli", name: "Salli Systems", country: "FI", tier: "premium", founded_year: 1990 },
  { slug: "bambach", name: "Bambach", country: "AU", tier: "premium", founded_year: 1988 },
]
