import { z } from "zod"
export const finderSessionKey = "chairpedia-finder-session-v2"
const numeric = z.number().finite()
const range = z.object({ min: numeric, max: numeric }).nullable()
const fit = z.object({ status: z.enum(["good", "conditional", "insufficient-data"]), confidence: z.enum(["high", "medium", "limited"]), score: numeric, evidence: z.array(z.string()), conflicts: z.array(z.string()), unknowns: z.array(z.string()), measurements: z.object({ seatHeightCm: range, seatDepthCm: range, seatWidthCm: numeric.nullable(), capacityKg: numeric.nullable(), armrestFloorHeightCm: range }), components: z.object({ bodyHeight: numeric.nullable(), seatHeight: numeric.nullable(), seatDepth: numeric.nullable(), weightCapacity: numeric.nullable(), deskClearance: numeric.nullable() }) })
const chair = z.object({ id: z.string(), slug: z.string(), name: z.string(), brand: z.string().nullable(), image: z.string().nullable(), priceRange: z.string().nullable(), fitStatus: fit.shape.status, fitConfidence: fit.shape.confidence, fit, sourceUpdatedAt: z.string().nullable(), fitEvidence: z.array(z.object({ fieldKey: z.string(), evidenceType: z.string(), sourceTitle: z.string(), sourceUrl: z.string(), checkedOn: z.string(), notes: z.string().optional() })).optional(), awards: z.array(z.object({ id: z.string(), title: z.string(), reason: z.string() })).optional(), strongAlternative: z.boolean().optional(), alternativeReason: z.string().nullable().optional() })
const answers = z.object({ height: numeric.min(120).max(230).optional(), weight: numeric.min(30).max(250).optional(), desk: numeric.min(45).max(140).optional(), unknownDesk: z.boolean(), underDesk: z.boolean(), keyboardTray: z.boolean(), posture: z.string(), hours: z.string(), concerns: z.array(z.string()).max(6), material: z.string(), priorities: z.array(z.enum(["headrest","recline","lumbar","arms","seatdepth","warranty","value","design"])).max(4), country: z.string(), budget: numeric.min(0).optional(), condition: z.string(), shopping: z.string(), unit: z.enum(["metric","imperial"]) })
export const recommendationPayloadSchema = z.object({ profile: z.object({ suggestedSeatHeightCm: range, suggestedSeatDepthCm: range, deskSeatGapCm: range, notes: z.array(z.string()) }), results: z.array(chair), standouts: z.array(chair).optional(), alternatives: z.array(chair).optional(), signature: z.string().optional(), showrooms: z.array(z.object({ productSlug: z.string(), finderPath: z.string(), exactTrialCount: numeric, brandStoreCount: numeric })).optional() })
export const finderSessionSchema = z.object({ version: z.literal(2), savedAt: numeric, stage: z.enum(["opening","body","desk","preferences","passport"]), step: z.number().int().min(0).max(9), activeChair: z.number().int().min(0).max(50), answers, requestKey: z.string(), payload: recommendationPayloadSchema.nullable() })
export function readFinderSession(storage: Pick<Storage,"getItem">, now = Date.now()) {
  try { const result = finderSessionSchema.safeParse(JSON.parse(storage.getItem(finderSessionKey) || "null")); return result.success && now - result.data.savedAt < 24 * 60 * 60 * 1000 && now >= result.data.savedAt ? result.data : null } catch { return null }
}
